### ISSUE TITLE
Schema name for drop-seq in fastq2bam

### ISSUE THREAD

**Issue by anjaf** [nunofonseca/fastq_utils#10]
Hi Nuno,

We've ran the fastq2bam converter for a drop-seq experiment and we've noticed that the schema name differs between the usage string ("drop-seq") and the actual expected schema name ("dropseq").
Can you change that to "drop-seq" everywhere to be consistent with our nomenclature? 

Thanks and best wishes,
Anja

**Comment by nunofonseca** [comment]
Hi Anja,
Thanks for pointing out the inconsistency. It is fixed now. 
Cheers.
