### ISSUE TITLE
PacBio quality encoding range

### ISSUE THREAD

**Issue by anjaf** [nunofonseca/fastq_utils#11]
Hi Nuno, 

Long time no see :) Hope you are well. I've got a new issue for you: 

We've now seen a few cases where FASTQ files from PacBio fail fastq validation with the error 
`Unable to determine quality encoding - unknown range [34,123] `.
Although the actual numbers in the range vary from file to file. 

Can this be added as allowed? 
Unfortunately, I haven't found out what the maximum value or the expected range should be.
Let me know if you need more details. 

Anja

**Comment by anjaf** [comment]
Forgot to mention that the same problem seems to occur for Oxford Nanopore data.

**Comment by nunofonseca** [comment]
Hi Anja,
All good here. Hope that you are well too.
The new version (released a few minutes ago) supports the encoding used in Nanopore and Pacbio data.
Please let me know if you encounter any problem.
Cheers.

**Comment by nunofonseca** [comment]
Hi Anya,
Just to let you know that I patched the last version to fix an issue regarding the encoding of Nanopre/pacbio data, you may want to upgrade to the latest version (0.24.1).
Cheers.

**Comment by anjaf** [comment]
Thanks Nuno!
