### ISSUE TITLE
Fatal error when attempting 'make'

### ISSUE THREAD

**Issue by mshadbolt** [nunofonseca/fastq_utils#13]
After downloading and attempting the make step I get the following error:
`fastq_pre_barcodes.c:34:17: fatal error: bam.h: No such file or directory`

I first tried with latest, and then tried with the previous minor version.

Full output

```
mshadbolt@ip-172-31-71-222:~/software/fastq_utils-0.23.0$ make
make -C src clean
make[1]: Entering directory '/home/mshadbolt/software/fastq_utils-0.23.0/src'
rm -f *.o fastq_truncate fastq_filterpair  fastq_filter_n fastq_num_reads fastq_not_empty fastq_pre_barcodes fastq_trim_poly_at fastq_split_interleaved fastq_tests bam_add_tags bam_umi_count bam2fastq fastq_info *~
make[1]: Leaving directory '/home/mshadbolt/software/fastq_utils-0.23.0/src'
make -C src
make[1]: Entering directory '/home/mshadbolt/software/fastq_utils-0.23.0/src'
gcc -I ../samtools-0.1.19 -O3 -Wunused-result  -Wall   -c fastq_truncate.c
gcc -O3 -Wunused-result  -Wall -c hash.c
gcc -O3 -Wunused-result  -Wall -I ../zlib-1.2.11 -lz -c fastq.c 
gcc  -O3 -Wunused-result  -Wall fastq_truncate.o hash.o fastq.o -lz -o fastq_truncate  
gcc -I ../samtools-0.1.19 -O3 -Wunused-result  -Wall   -c fastq_filterpair.c
gcc  -O3 -Wunused-result  -Wall hash.o fastq_filterpair.o fastq.o -lz -o fastq_filterpair
gcc -I ../samtools-0.1.19 -O3 -Wunused-result  -Wall   -c fastq_filter_n.c
gcc  -O3 -Wunused-result  -Wall fastq_filter_n.o fastq.o hash.o -lz -o fastq_filter_n 
gcc -I ../samtools-0.1.19 -O3 -Wunused-result  -Wall   -c fastq_num_reads.c
gcc  -O3 -Wunused-result  -Wall fastq_num_reads.o hash.o fastq.o -lz -o fastq_num_reads 
gcc -I ../samtools-0.1.19 -O3 -Wunused-result  -Wall   -c fastq_not_empty.c
gcc  -O3 -Wunused-result  -Wall fastq_not_empty.o hash.o fastq.o -lz -o fastq_not_empty 
gcc -I ../samtools-0.1.19 -O3 -Wunused-result  -Wall   -c fastq_pre_barcodes.c
fastq_pre_barcodes.c:34:17: fatal error: bam.h: No such file or directory
compilation terminated.
Makefile:106: recipe for target 'fastq_pre_barcodes.o' failed
make[1]: *** [fastq_pre_barcodes.o] Error 1
make[1]: Leaving directory '/home/mshadbolt/software/fastq_utils-0.23.0/src'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by johnbakerh** [comment]
I also receive the same issue

**Comment by nunofonseca** [comment]
Hi,

Did you install the dependencies (zlib and samtools 0.1.9)?

"samtools (version 0.1.19) and zlib (http://zlib.net) version 1.2.11 or latest are required to compile fastq_utils. The install_deps.sh script in the toplevel folder tries to download and compile the dependencies. "

Cheers.

**Comment by johnbakerh** [comment]
@nunofonseca Do these dependencies need to be located in the same directory? I tried installing these dependencies on my machine and still continued to get this error...  

In home directory: 
```
wget https://github.com/samtools/samtools/releases/download/1.9/samtools-1.9.tar.bz2
tar -vxjf samtools-1.9.tar.bz2
cd samtools-1.9
make
```

and similar process for installing Zlib....

**Comment by johnbakerh** [comment]
@nunofonseca I did a clean install and, installed dependencies samtools and Zlib, still producing same error...

**Comment by nunofonseca** [comment]
Yes, the Makefile assumes that samtools is installed in the same directory. 
You should be able to compile successfully by running the following commands:
`
./install_deps.sh
make
make install
`

**Comment by johnbakerh** [comment]
@nunofonseca 

The previous error was not present anymore but now I encounter the following error, not sure if you are aware of this as well:

```
gcc  -O3 -Wunused-result  -Wall hash.o fastq_info.o fastq.o -lz -o fastq_info
make[1]: Leaving directory `/home/user/fastq_utils/src'
make: *** No rule to make target `intstall'.  Stop.


```

**Comment by nunofonseca** [comment]
The error seems to be a consequence of a typo: you probably wrote intstall instead of install (make install). The fastq_info and other programs will be copied to the bin/ folder in the toplevel fastq_utils directory.

**Comment by johnbakerh** [comment]
@nunofonseca thanks for the clarification, everything is working fine. you can close this issue if needed.

**Comment by nunofonseca** [comment]
Instead of
`export PATH="/home//user/fastq_utils/:$PATH"`
you may want to do
`export PATH="/home//user/fastq_utils/bin/:$PATH"`
?
Alternatively, you can simply copy the files in the fastq_utils/bin folder to a folder that is already in the $PATH.

**Comment by mshadbolt** [comment]
thanks for the debugging, I was successfully able to install now.
