### ISSUE TITLE
Add support for Nanopore RNA-seq data to FASTQ validator

### ISSUE THREAD

**Issue by anjaf** [nunofonseca/fastq_utils#15]
Hi Nuno (hope you are doing well!), 

We have a new request for you. We have people submitting their Oxford Nanopore RNA-sequencing data in FASTQ format. These naturally contain 'U' bases instead of 'T's. The fastq validator currently rejects these for containing 'U' characters as unknown (`invalid character 'U' (hex. code:'55'), expected ACGTacgt0123nN.`). 
ENA is happy to accept such sequences (example file: ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR431/ERR4319899/PCreads.fastq.gz) and thus, we would like to relax the fastq validation rules and have it accept files with sequences containing U characters.

**Comment by nunofonseca** [comment]
Hi! My best to everyone! :-)
Please check the new version (0.25.1) - it now supports reads with Us instead of Ts but it will fail if Us and Ts appear in the same read. Let me know if you encounter any problem.
Cheers

**Comment by anjaf** [comment]
Thank you @nunofonseca! Will let you know of any issues.
