### ISSUE TITLE
SAM UMI tags vs 10X chromium molecular barcode tags

### ISSUE THREAD

**Issue by sandrobe-nih** [nunofonseca/fastq_utils#5]
Not sure if your UMI tags are meant to support 10X or another technology but just in case, the tags for the Chromium molecular barcode are UB (corrected barcode) and UY from 'https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/output/bam' rather than RX and QX. Perhaps of interest to you.

Kind regards

**Comment by nunofonseca** [comment]
Hi,
The UMI tags currently used follow the SAM specification. I will add an option to alternatively use the 10x.
Cheers.

**Comment by sandrobe-nih** [comment]
Thanks!
