### ISSUE TITLE
Duplicated Arguments

### ISSUE THREAD

**Issue by Ahmed-Gemmy** [nunofonseca/fastq_utils#7]
Hi Nuno,
the fastq2bam has duplicated arg '-s'
it is used for both `schema` and for `sample barcode offset` which was added as a response to Anja's issue #1

Thanks.

**Comment by nunofonseca** [comment]
Hi!, You are right!
 I changed -s and -S to -z and -Z to avoid name clashing. I will release a new version with the fix after confirming that all tests passed. 

Cheers.
