### ISSUE TITLE
Add 10xV3 schema

### ISSUE THREAD

**Issue by anjaf** [nunofonseca/fastq_utils#9]
Hi Nuno, 

10x has now released version 3 and we've been getting a few submissions already with the new library schema. 
Could you add the 10xV3 schema to the converter? I think all that has changed from our point of view is that the UMI barcode is now 12 bp instead of 10 bp (compared to 10xV2). 

Thanks and best wishes,
Anja

**Comment by nunofonseca** [comment]
Hi Anja,

Thanks for the issue. I was already working on this so it should be done quickly.

Cheers.

**Comment by nunofonseca** [comment]
Version 0.22.0 is out with support for the 10xV3 schema.  Thanks!

**Comment by anjaf** [comment]
Wow, that was quick. Thanks, Nuno!
